// This file was automatically generated by the Dapper.SimpleCRUD T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `testdb`
//     Provider:               `System.Data.SqlServerCe.4.0`
//     Connection String:      `Data Source=C:\Users\ecoffman\Documents\GitHub\Dapper.SimpleCRUD\SampleWebsite\App_Data\Test.sdf;Persist Security Info=False;`
//     Include Views:          `True`

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SampleWebsite.Models
{
    /// <summary>
    /// A class which represents the Car table.
    /// </summary>
	[Table("Car")]
	public partial class Car
	{
		[Key]
		public virtual int CarId { get; set; }
		public virtual string Make { get; set; }
		public virtual string Model { get; set; }
	}

    /// <summary>
    /// A class which represents the Users table.
    /// </summary>
	[Table("Users")]
	public partial class User
	{
		public virtual int Id { get; set; }
		public virtual int? Age { get; set; }
		public virtual string FirstName { get; set; }
		public virtual string LastName { get; set; }
	}

}
