// This file was automatically generated by the Dapper.SimpleCRUD T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `testdb`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source = (LocalDB)\v11.0;Initial Catalog=SimplecrudDemoWebsite;Integrated Security=True;`
//     Include Views:          `True`


// -----------------------------------------------------------------------------------------
// Failed to read database schema - Cannot open database "SimplecrudDemoWebsite" requested by the login. The login failed. Login failed for user 'HS\ecoffman'.
// -----------------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DemoWebsite.GeneratorExample.Models
{
}
